<?php

$_CONFIG = array(
    'lang' => 'ru',
    'title_site' => 'Генератор QR кода',
    'description' => 'Необходимо создать QR код? QR Generator - полностью настраиваемый, бесплатный, не имеющий ограничений и не требующий регистрации онлайн генератор QR кода. Создайте QR код в несколько простых кликов!',
    'qrcodes_dir' => 'qrcodes',
    'delete_old_files' => true,
    'file_lifetime' => 24,
    'uploader' => true,
    'upload_max_filesize' => 1000,
    'thumb_size' => 130,
    'qr_bgcolor' => '#FFFFFF',
    'qr_color' => '#000000',
    'session_name' => 'qrSession',
    'placeholder' => 'images/placeholder.svg',
    'logo_header' => 'logo.png',
    'logo_footer' => 'logo-alt.png',
    'vkontakte' => 'https://vk.com/',
	'odnoklassniki' => 'https://ok.ru/',
	'youtube' => 'https://www.youtube.com/',
    'main_title' => 'Бесплатный онлайн генератор QR кода',
    'main_subtitle' => 'Необходимо создать QR код? QR Generator - полностью настраиваемый, бесплатный, не имеющий ограничений и не требующий регистрации онлайн генератор QR кода. Создайте QR код в несколько простых кликов!',
    'main_name_button' => 'Создать QR код',
    'main_url_button' => '#create_qr',
    'main_image' => 'mobile.png',
    'advantage_one' => 'Уникальный дизайн',
	'main_description_one' => 'Создайте собственный дизайн QR кода. Добавьте цвета своего бренда и логотип вашей компании',
	'advantage_two' => '10+ типов QR кода',
	'main_description_two' => 'Выберите тип QR кода в зависимости от типа передаваемой информации и создайте свой QR код.',
	'advantage_three' => 'Скачивание в PNG и SVG',
	'main_description_three' => 'Скачивайте свой QR код в необходимом формате. Наносите его на ваши рекламные буклеты или визитки.',
    'instructions_title' => 'Как создать QR код?',
	'instructions_subtitle' => 'Процесс создания QR кода весьма прост и интуитивно понятен - всего за несколько кликов, генератор поможет Вам закодировать всю желаемую информацию для последующего использования.<br><br>1. Выберите категорию, которую необходимо закодировать (ссылка, местоположение, номер телефона, визитная карточка и т.д.);<br>2. Заполните все обязательные поля;<br>3. Выберите цвета и загрузите логотип;<br>4. Нажмите ГЕНЕРИРОВАТЬ QR-КОД;',
	'instructions_image' => 'feature-new-01.jpg',
    'generator_title' => 'Создайте ваш собственный QR-код с логотипом',
    'generator_description' => 'Хотите, чтобы ваш QR-код был уникальным? Выберите для него собственный цвет и нестандартную форму. Угловые элементы и основную часть кода можно настроить по отдельности. Добавьте логотип к вашему QR-коду',
    'promo_title' => 'Смотрите наше промо-видео',
	'promo' => 'https://youtu.be/iCMRqcC__Rk',
    'ads' => '<a href="#" target="_blank"><img class="image thumb__image" src="https://avatars.mds.yandex.net/get-direct-picture/103005/J0nFCI3tGqBQ45y3OVt7qQ/orig" style="width:100%;height:auto;object-fit: contain;" aria-hidden="true"></a>',
    'galleries_title' => 'Примеры QR кодов',
	'galleries_desc' => 'Отсканируйте любой QR код и посмотрите результат',
    'image_one' => 'images/qr-code/vkusno_i_tochka.png',
	'image_two' => 'images/qr-code/shinomontag.png',
	'image_three' => 'images/qr-code/sushi.png',
	'image_four' => 'images/qr-code/marketolog.png',
    'text_image_one' => '',
	'text_image_two' => '',
	'text_image_three' => '',
	'text_image_four' => 'Сообщение в WhatsApp',
    'text_footer' => 'Генератор QR кода — один из самых популярных бесплатных онлайн-генераторов, с помощью которого созданы уже миллионы QR-кодов. Высокое разрешение QR-кодов и многофункциональные возможности дизайна делают его одним из лучших бесплатных генераторов QR-кодов в Интернете, который можно использовать для печати и в коммерческих целях.',
    'link' => true,
    
    'email' => true,
    'text' => true,
    'tel' => true,
    'sms' => true,
    'whatsapp' => true,
    
    
    
    
    'paypal' => true,
    'bitcoin' => true,
    'default_tab' => '#vcard',
    'detect_browser_lang' => false,
    'google_api_key' => '',
    'color_primary' => '#2e7eed',
    'username' => 'admin',
    'password' => 'b59c67bf196a4758191e42f76670ceba',
    'install' => '1',
    );

?>